--plugins
require("plugins.plugins")
--functionaltiy
require("fun.keymaps")
require("fun.options")
require("fun.autopairs")
--require("fun.bufline")
require("fun.barbar")
require("fun.comment")
require("fun.nvimtree")
require("fun.telescope")
--lsp
require("lsp.cmp")
require("lsp.mason")
require("lsp.lspservers")
require("lsp.nullls")
--loosk
require("looks.theme")
require("looks.treesitter")
require("looks.gitsigns")
require("looks.blankline")
require("looks.lualine")
